"use client";

import ImageComparison from "@/components/ImageComparison";
import { useMemo, useRef, useState } from "react";
import {
  Check,
  CheckCircle2,
  ChevronRight,
  Copy,
  Eye,
  FileImage,
  Lock,
  RefreshCw,
  ShieldCheck,
  Sparkles,
  Upload,
  X,
} from "lucide-react";

import type { AppMode, AppStep, Detection } from "@/types";

import {
  hashFile,
  loadRgbaImage,
  rgbaToPngBlob,
  sha256Bytes,
  shortHash,
} from "@/lib/image-utils";
import { vision } from "truemask-api";

/**
 * Detection, block-splitting, hashing and redaction all live in the shared
 * pipeline (`api/src/vision`), not in this component. That matters: the regions
 * the journalist sees here and the blocks the circuit hashes have to come from
 * one implementation, or the UI can show one thing while the proof commits to
 * another.
 */
type PixelDetection = vision.Detection;
type RedactionResult = vision.RedactionResult;

type StepDefinition = { id: AppStep; label: string };

const PROTECT_STEPS: StepDefinition[] = [
  { id: "upload", label: "Upload" },
  { id: "scan", label: "Scan" },
  { id: "review", label: "Review" },
  { id: "redact", label: "Protect" },
  { id: "compare", label: "Compare" },
  { id: "verified", label: "Verify" },
];

/**
 * Verifying is a much shorter journey: there is nothing to detect and nothing to
 * redact in an image that has already been published, so the scan, review and
 * redaction steps do not apply.
 */
const VERIFY_STEPS: StepDefinition[] = [
  { id: "upload", label: "Upload" },
  { id: "verifyId", label: "Record ID" },
  { id: "verifyResult", label: "Result" },
];

import {
  CONTRACT_ADDRESS,
  FAUCET_URL,
  lookupRecordOnChain,
  useMidnight,
} from "@/hooks/useMidnight";

/**
 * The pipeline works in pixels; the UI positions overlays in percentages.
 * These two helpers are the only place the two coordinate systems meet.
 */
function toUiDetection(
  item: PixelDetection,
  index: number,
  image: ImageData,
): Detection {
  const type: Detection["type"] = item.kind === "face" ? "face" : "text";
  return {
    id: `${item.kind}-${index}`,
    type,
    label:
      item.kind === "face" ? "Face" : item.text ? `Text: ${item.text}` : "Text",
    risk: item.kind === "face" ? "critical" : "high",
    x: (item.box.x / image.width) * 100,
    y: (item.box.y / image.height) * 100,
    width: (item.box.width / image.width) * 100,
    height: (item.box.height / image.height) * 100,
    selected: true,
  };
}

/** Where the publish action currently is. Only ever used by the protect flow. */
type PublishState =
  | { status: "idle" }
  | { status: "connecting" }
  | { status: "publishing" }
  | { status: "done"; txId?: string; contractAddress?: string }
  | { status: "error"; message: string; needsFunds?: boolean; timedOut?: boolean };

/** Whether a verified record was also found on Midnight. */
type OnChainStatus = "unchecked" | "checking" | "found" | "absent" | "unavailable";

/**
 * Turn an SDK failure into something a journalist can act on.
 *
 * The one case worth special handling is having no tDUST, because the fix is a
 * specific three-step errand rather than "try again": the faucet dispenses
 * tNIGHT to your unshielded address, and tDUST is then generated by delegating
 * that NIGHT in the wallet, which takes a minute or two to accrue.
 */
function describePublishError(err: unknown): {
  message: string;
  needsFunds: boolean;
  timedOut: boolean;
} {
  const raw = err instanceof Error ? err.message : String(err);
  return {
    message: raw,
    needsFunds: /dust|insufficient|balance|not enough|funds|fee/i.test(raw),
    timedOut: err instanceof TimeoutError,
  };
}

class TimeoutError extends Error {}

/**
 * Bounds a wallet call that has no timeout of its own. Preprod's RPC WebSocket
 * has been unreliable enough, for us and for other teams at this hackathon,
 * that a bare `await` here can hang the publish button indefinitely with no
 * way to recover except reloading the page. `phase` only labels which stage
 * timed out, for the error message.
 */
function withTimeout<T>(promise: Promise<T>, ms: number, phase: "connect" | "publish"): Promise<T> {
  return new Promise((resolve, reject) => {
    const timer = window.setTimeout(
      () => reject(new TimeoutError(`Timed out waiting to ${phase}.`)),
      ms,
    );
    promise.then(
      (value) => { window.clearTimeout(timer); resolve(value); },
      (err) => { window.clearTimeout(timer); reject(err); },
    );
  });
}

const toHexString = (bytes: Uint8Array): string =>
  [...bytes].map((byte) => byte.toString(16).padStart(2, "0")).join("");

function toPixelDetection(item: Detection, image: ImageData): PixelDetection {
  return {
    kind: item.type === "face" ? "face" : "text",
    confidence: 1,
    box: {
      x: (item.x / 100) * image.width,
      y: (item.y / 100) * image.height,
      width: (item.width / 100) * image.width,
      height: (item.height / 100) * image.height,
    },
  };
}

export default function TrueMaskApp() {
  const inputRef = useRef<HTMLInputElement>(null);

  const { address, isConnecting, connect, isWalletAvailable, getApi } =
    useMidnight();

  const [step, setStep] = useState<AppStep>("upload");
  /** null until the user picks a path on the landing screen. */
  const [mode, setMode] = useState<AppMode | null>(null);
  const [file, setFile] = useState<File | null>(null);
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [detections, setDetections] = useState<Detection[]>([]);
  const [manualDetections, setManualDetections] = useState<Detection[]>([]);
  const [originalHash, setOriginalHash] = useState("");
  const [protectedHash, setProtectedHash] = useState("");
  const [isDragging, setIsDragging] = useState(false);
  const [status, setStatus] = useState<string | null>(null);
  /** Whether the AI model is currently being downloaded from the CDN (first run only). */
  const [modelLoading, setModelLoading] = useState(false);
  /** The decoded original pixels. Held so the protect step hashes what was scanned. */
  const sourcePixels = useRef<ImageData | null>(null);
  /** Object URL of the real redacted PNG. This is what the "protected" panels show. */
  const [redactedUrl, setRedactedUrl] = useState<string | null>(null);
  /** Verify path: SHA-256 of the uploaded published image, and the ID typed in. */
  /**
   * The finished redaction, kept so publishing can happen later as its own
   * deliberate step. Previously the transaction fired automatically at the end
   * of protectImage(), which meant a blockchain write with no user consent.
   */
  const publishable = useRef<{ hash: Uint8Array; redaction: RedactionResult } | null>(null);
  const [publish, setPublish] = useState<PublishState>({ status: "idle" });
  const publishAttempt = useRef(0);
  /** Verify path: whether the record was also found on Midnight. */
  const [onChain, setOnChain] = useState<OnChainStatus>("unchecked");
  const [checkedHash, setCheckedHash] = useState("");
  const [verificationId, setVerificationId] = useState("");

  const steps = mode === "verify" ? VERIFY_STEPS : PROTECT_STEPS;
  const currentStepIndex = steps.findIndex((item) => item.id === step);

  const allDetections = [...detections, ...manualDetections];
  const selectedDetections = useMemo(
    () => allDetections.filter((item) => item.selected),
    [allDetections],
  );

  async function handleFile(selectedFile: File) {
    if (!selectedFile.type.startsWith("image/")) {
      alert("Please upload an image file.");
      return;
    }

    const url = URL.createObjectURL(selectedFile);

    setFile(selectedFile);
    setImageUrl(url);
    setDetections([]);

    // Verifying only needs the file's hash — no detection, no redaction.
    if (mode === "verify") {
      setStatus(null);
      try {
        setCheckedHash(await hashFile(selectedFile));
        setStep("verifyId");
      } catch {
        setStatus("Could not read that image.");
      }
      return;
    }

    setStep("scan");

    try {
      const hash = await hashFile(selectedFile);
      setOriginalHash(hash);

      const image = await loadRgbaImage(url);
      sourcePixels.current = image;

      // Faces via MediaPipe, signs and documents via OCR — both from the shared
      // pipeline, so these are the same boxes the redaction will use.
      //
      // Run independently: Tesseract downloads language data on first use and is
      // the more fragile of the two. Awaiting both in one array meant an OCR
      // failure threw away perfectly good face detections as well.
      setModelLoading(true);
      setStatus("Loading AI model (first run downloads ~20 MB)…");
      // Warm up the face model so we can show loading state before scanning
      // detectFaces handles caching internally — subsequent calls are instant.
      try {
        await vision.detectFaces(image, { minConfidence: 2 }); // minConfidence: 2 = impossible, so 0 results but model is warmed
      } catch {
        // ignore — we just wanted to load the model
      }
      setModelLoading(false);
      setStatus("Scanning for faces and text…");
      const [faces, text] = await Promise.allSettled([
        vision.detectFaces(image),
        vision.detectText(image, { minConfidence: 0.75 }),
      ]);

      const found: PixelDetection[] = [
        ...(faces.status === "fulfilled" ? faces.value : []),
        // Filter text more aggressively: require minimum 24x12 px (1.5x the block size)
        // to reduce noise from logos, icons, and artifacts while keeping readable text
        ...(text.status === "fulfilled"
          ? text.value.filter(
              (item) => item.box.width >= 24 && item.box.height >= 12,
            )
          : []),
      ];

      const failures = [
        faces.status === "rejected" ? "face detection" : null,
        text.status === "rejected" ? "text detection" : null,
      ].filter(Boolean);
      if (faces.status === "rejected")
        console.error("Face detection failed:", faces.reason);
      if (text.status === "rejected")
        console.error("Text detection failed:", text.reason);

      const faceCount = found.filter((d) => d.kind === "face").length;
      const textCount = found.filter((d) => d.kind === "text").length;

      let statusMessage = "";
      if (failures.length) {
        statusMessage = `⚠️ ${failures.join(" and ")} unavailable — showing ${found.length} region(s) from the rest. Add any missed area by hand before protecting.`;
      } else if (found.length === 0) {
        statusMessage =
          "ℹ️ No faces or text detected. Carefully review the image and manually add any sensitive areas before protecting.";
      } else {
        statusMessage = `✓ Detected ${faceCount} face(s) and ${textCount} text region(s). Review and adjust before protecting.`;
      }

      setStatus(statusMessage);
      setDetections(
        found.map((item, index) => toUiDetection(item, index, image)),
      );
      setStep("review");
    } catch (err) {
      console.error("Scan failed:", err);
      setStatus(err instanceof Error ? err.message : "Scan failed.");
      setDetections([]);
      setStep("review");
    }
  }

  function toggleDetection(id: string) {
    // Check if it's a detected region or manual region
    const inDetected = detections.some((d) => d.id === id);

    if (inDetected) {
      setDetections((current) =>
        current.map((item) =>
          item.id === id ? { ...item, selected: !item.selected } : item,
        ),
      );
    } else {
      setManualDetections((current) =>
        current.map((item) =>
          item.id === id ? { ...item, selected: !item.selected } : item,
        ),
      );
    }
  }

  function removeDetection(id: string) {
    // Remove from manual detections
    setManualDetections((current) => current.filter((item) => item.id !== id));
  }

  async function protectImage() {
    const image = sourcePixels.current;
    if (!file || !imageUrl || !image) return;

    setStep("redact");
    setStatus(null);

    try {
      // One call does the whole thing: grid, block mapping, block hashes, the
      // preserved root, the bitmap commitment and the blacked-out pixels.
      // Solid blackout only, never a soft cover: Gaussian blur and pixelation
      // are both reversible enough to attack, and this exists to protect sources.
      const totalBlocks =
        Math.ceil(image.width / 16) * Math.ceil(image.height / 16);
      setStatus(`Hashing ${totalBlocks.toLocaleString()} blocks…`);
      const redaction = await new Promise<vision.RedactionResult>(
        (resolve, reject) => {
          const worker = new Worker(
            new URL("../workers/redact.worker.ts", import.meta.url),
          );
          worker.onerror = (err) => {
            worker.terminate();
            reject(
              new Error(
                "Worker error: " + (err.message || "failed to load script"),
              ),
            );
          };
          worker.onmessage = (e) => {
            if (e.data.type === "progress") {
              setStatus(
                `Hashing blocks… ${Math.round((e.data.done / e.data.total) * 100)}%`,
              );
            } else if (e.data.type === "done") {
              worker.terminate();
              resolve(e.data.redaction);
            } else if (e.data.type === "error") {
              worker.terminate();
              reject(new Error(e.data.error));
            }
          };
          worker.postMessage({
            image,
            detections: selectedDetections.map((item) =>
              toPixelDetection(item, image),
            ),
          });
        },
      );

      // PNG, never JPEG. JPEG re-quantises every block, which changes bytes
      // outside the redacted regions and breaks the proof for everyone.
      const pngBlob = await rgbaToPngBlob(redaction.redactedImage);
      const pngBytes = await pngBlob.arrayBuffer();
      const redactedHash = await sha256Bytes(pngBytes);
      setProtectedHash(toHexString(redactedHash));

      // This is the image the app actually protected. Previously it was hashed
      // and then dropped, and every "protected" panel rendered the original.
      setRedactedUrl((previous) => {
        if (previous) URL.revokeObjectURL(previous);
        return URL.createObjectURL(pngBlob);
      });

      // Publishing is a blockchain write. It now waits for an explicit action on
      // the record screen instead of firing as a side effect of redacting.
      publishable.current = { hash: redactedHash, redaction };
      setPublish({ status: "idle" });
      setStatus("Redaction complete and verifiable offline.");

      setStep("verified");
    } catch (err) {
      console.error("Protection failed:", err);
      setProtectedHash("Unable to generate hash");
      setStatus(err instanceof Error ? err.message : "Protection failed.");
    }

    window.setTimeout(() => {
      setStep("compare");
    }, 1800);
  }

  /**
   * Connect (if needed) and submit the redaction record to Midnight.
   *
   * Only ever reachable from the protect flow. The verify flow never calls this
   * and never touches a provider — checking a record is a read.
   */
  async function publishRecord() {
    const pending = publishable.current;
    if (!pending) return;

    // Preprod's RPC WebSocket has documented reliability issues (other teams at
    // this hackathon hit the same wall: HTTP endpoints healthy, WS sync never
    // completes). Without a timeout, a hang here freezes the button forever with
    // no way out mid-demo. This generation counter lets "Cancel" abandon a
    // stuck attempt safely: if the old promise resolves late, it's ignored
    // rather than clobbering whatever the user did next.
    const attempt = ++publishAttempt.current;
    const stillCurrent = () => publishAttempt.current === attempt;

    try {
      setPublish({ status: address ? "publishing" : "connecting" });
      if (!address) await withTimeout(connect(), 20_000, "connect");

      if (!stillCurrent()) return;
      setPublish({ status: "publishing" });
      const api = await withTimeout(getApi(), 20_000, "connect");
      const receipt = await withTimeout(
        api.submitRedaction(pending.hash, pending.redaction),
        60_000,
        "publish",
      );

      if (!stillCurrent()) return;
      setPublish({
        status: "done",
        txId: receipt?.txId || undefined,
        contractAddress: receipt?.contractAddress || CONTRACT_ADDRESS,
      });
      setStatus("Record published to Midnight.");
    } catch (err) {
      if (!stillCurrent()) return;
      console.error("Publish failed:", err);
      setPublish({ status: "error", ...describePublishError(err) });
    }
  }

  /** Abandon whatever publish attempt is in flight and return the button to idle. */
  function cancelPublish() {
    publishAttempt.current++;
    setPublish({ status: "idle" });
  }

  function resetApp() {
    if (imageUrl) {
      URL.revokeObjectURL(imageUrl);
    }
    if (redactedUrl) {
      URL.revokeObjectURL(redactedUrl);
    }

    setFile(null);
    setImageUrl(null);
    setRedactedUrl(null);
    setStatus(null);
    setDetections([]);
    setManualDetections([]);
    setMode(null);
    publishable.current = null;
    setPublish({ status: "idle" });
    setOnChain("unchecked");
    setCheckedHash("");
    setVerificationId("");
    setOriginalHash("");
    setProtectedHash("");
    setStep("upload");
  }

  /**
   * The published image's commitment is the SHA-256 of the exact bytes that were
   * protected, so re-hashing the file the reader received and comparing is a real
   * cryptographic check — it needs no wallet and no network.
   */
  const verificationPassed =
    checkedHash.length > 0 &&
    checkedHash === verificationId.trim().toLowerCase().replace(/^0x/, "");

  return (
    <main className="min-h-screen px-4 py-5 md:px-10">
      <header className="mx-auto flex w-full max-w-7xl items-center justify-between gap-2">
        <button onClick={resetApp} className="flex items-center gap-2 shrink-0">
          <div className="flex h-9 w-9 items-center justify-center rounded-xl border border-white/10 bg-white/5">
            <ShieldCheck size={18} />
          </div>

          <div className="text-left">
            <div className="text-base font-bold tracking-tight">TrueMask</div>
            <div className="hidden text-xs text-white/45 sm:block">Privacy with proof</div>
          </div>
        </button>

        <div className="flex items-center gap-2 md:gap-4">
          {address ? (
            <div className="rounded-lg border border-green-500/30 bg-green-500/10 px-3 py-1.5 text-xs text-green-400 md:px-4 md:py-2 md:text-sm">
              <span className="hidden sm:inline">Connected: </span>{address.slice(0, 6)}…
            </div>
          ) : isWalletAvailable ? (
            <button
              onClick={connect}
              disabled={isConnecting}
              className="rounded-lg border border-white/10 px-3 py-1.5 text-xs text-white/70 transition hover:bg-white/5 disabled:opacity-50 md:px-4 md:py-2 md:text-sm"
            >
              {isConnecting ? "Connecting..." : "Connect wallet"}
            </button>
          ) : null}
          {step !== "upload" && (
            <button
              onClick={resetApp}
              className="rounded-lg border border-white/10 px-3 py-1.5 text-xs text-white/70 transition hover:bg-white/5 md:px-4 md:py-2 md:text-sm"
            >
              New image
            </button>
          )}
        </div>
      </header>

      <section className="mx-auto mt-8 max-w-4xl md:mt-10">
        {mode && (
          <div className="mb-10 flex items-center justify-between gap-2">
            {steps.map((item, index) => {
              const active = index <= currentStepIndex;

              return (
                <div key={item.id} className="flex flex-1 items-center gap-2">
                  <div
                    className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full border text-xs ${
                      active
                        ? "border-white bg-white text-black"
                        : "border-white/10 text-white/30"
                    }`}
                  >
                    {index < currentStepIndex ? <Check size={14} /> : index + 1}
                  </div>

                  <span
                    className={`hidden text-xs md:block ${
                      active ? "text-white" : "text-white/30"
                    }`}
                  >
                    {item.label}
                  </span>

                  {index < steps.length - 1 && (
                    <div
                      className={`h-px flex-1 ${
                        index < currentStepIndex ? "bg-white/70" : "bg-white/10"
                      }`}
                    />
                  )}
                </div>
              );
            })}
          </div>
        )}

        {status && (
          <p className="mx-auto mt-4 max-w-3xl text-center text-sm text-white/50">
            {status}
          </p>
        )}

        {step === "upload" && (
          <UploadScreen
            inputRef={inputRef}
            isDragging={isDragging}
            setIsDragging={setIsDragging}
            onFile={handleFile}
            mode={mode}
            onSelectMode={setMode}
          />
        )}

        {step === "verifyId" && (
          <VerifyIdScreen
            imageUrl={imageUrl}
            verificationId={verificationId}
            setVerificationId={setVerificationId}
            onCheck={() => {
              setStep("verifyResult");
              // A read, so no wallet is involved. Purely additive: verification
              // has already succeeded or failed locally by this point.
              setOnChain("checking");
              void lookupRecordOnChain(verificationId.trim()).then(setOnChain);
            }}
          />
        )}

        {step === "verifyResult" && (
          <VerifyResultScreen
            onChain={onChain}
            imageUrl={imageUrl}
            passed={verificationPassed}
            checkedHash={checkedHash}
            verificationId={verificationId}
            onBack={() => setStep("verifyId")}
            onReset={resetApp}
          />
        )}

        {step === "scan" && imageUrl && <ScanningScreen imageUrl={imageUrl} modelLoading={modelLoading} />}

        {step === "review" && imageUrl && (
          <ReviewScreen
            imageUrl={imageUrl}
            detections={allDetections}
            toggleDetection={toggleDetection}
            onAddManual={(detection) => {
              setManualDetections((current) => [
                ...current,
                { ...detection, selected: true },
              ]);
            }}
            onRemoveManual={removeDetection}
            onContinue={protectImage}
          />
        )}

        {step === "redact" && imageUrl && (
          <ProtectingScreen
            imageUrl={imageUrl}
            count={selectedDetections.length}
          />
        )}

        {step === "compare" && imageUrl && (
          <ImageComparison
            imageUrl={imageUrl}
            redactedUrl={redactedUrl}
            detections={selectedDetections}
            onContinue={() => setStep("verified")}
          />
        )}

        {step === "verified" && imageUrl && (
          <VerifiedScreen
            imageUrl={imageUrl}
            redactedUrl={redactedUrl}
            publish={publish}
            onPublish={publishRecord}
            onCancel={cancelPublish}
            isWalletAvailable={isWalletAvailable}
            detections={selectedDetections}
            originalHash={originalHash}
            protectedHash={protectedHash}
            onReset={resetApp}
          />
        )}
      </section>
    </main>
  );
}

/**
 * Landing screen.
 *
 * Two journeys start here and they are genuinely different, so the choice comes
 * before the dropzone rather than after it. Protect is emphasized as the likely
 * primary case, but Verify is a peer: same size, same hit area, same weight of
 * copy. The dropzone only appears once a path is picked, and its wording says
 * which image it wants.
 */
function UploadScreen({
  inputRef,
  isDragging,
  setIsDragging,
  onFile,
  mode,
  onSelectMode,
}: {
  inputRef: React.RefObject<HTMLInputElement | null>;
  isDragging: boolean;
  setIsDragging: (value: boolean) => void;
  onFile: (file: File) => void;
  mode: AppMode | null;
  onSelectMode: (mode: AppMode) => void;
}) {
  return (
    <div className="mx-auto max-w-3xl px-1 pt-8 text-center md:pt-10">
      <div className="mx-auto mb-6 flex h-14 w-14 items-center justify-center rounded-2xl border border-white/10 bg-white/5">
        <Lock size={24} />
      </div>

      <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl md:text-6xl">
        Protect sensitive information.
        <br />
        Prove what stayed unchanged.
      </h1>

      <p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-white/50 md:mt-6 md:text-base">
        Upload a photograph. Identify sensitive regions. Create a protected
        version with a verifiable integrity record.
      </p>

      <div className="mt-8 grid gap-4 sm:grid-cols-2 md:mt-10">
        <PathCard
          icon={<ShieldCheck size={20} />}
          title="Protect an image"
          hint="Start here"
          description="I have an original photo. I want to hide faces and other identifying details, then publish it with proof that nothing else was changed."
          selected={mode === "protect"}
          dimmed={mode === "verify"}
          onClick={() => onSelectMode("protect")}
        />

        <PathCard
          icon={<Eye size={20} />}
          title="Verify an image"
          description="I have an image someone published and a verification ID. I want to check that it matches the record and has not been altered."
          selected={mode === "verify"}
          dimmed={mode === "protect"}
          onClick={() => onSelectMode("verify")}
        />
      </div>

      {mode && (
        <div
          onDragOver={(event) => {
            event.preventDefault();
            setIsDragging(true);
          }}
          onDragLeave={() => setIsDragging(false)}
          onDrop={(event) => {
            event.preventDefault();
            setIsDragging(false);

            const droppedFile = event.dataTransfer.files?.[0];

            if (droppedFile) {
              onFile(droppedFile);
            }
          }}
          className={`mt-6 rounded-3xl border border-dashed p-8 transition md:p-12 ${
            isDragging
              ? "border-white bg-white/10"
              : "border-white/15 bg-white/[0.03]"
          }`}
        >
          <input
            ref={inputRef}
            type="file"
            accept="image/*"
            className="hidden"
            onChange={(event) => {
              const selectedFile = event.target.files?.[0];

              if (selectedFile) {
                onFile(selectedFile);
              }
            }}
          />

          <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-white text-black">
            <Upload size={22} />
          </div>

          <h2 className="mt-5 text-lg font-medium">
            {mode === "protect"
              ? "Upload the original photograph"
              : "Upload the published image to check"}
          </h2>

          <p className="mt-2 text-sm text-white/40">
            Drag and drop an image here or choose a file.
          </p>

          <button
            onClick={() => inputRef.current?.click()}
            className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-medium text-black transition hover:bg-white/90"
          >
            Choose image
            <ChevronRight size={16} />
          </button>

          <div className="mt-6 flex items-center justify-center gap-2 text-xs text-white/30">
            <Lock size={12} />
            {mode === "protect"
              ? "Original image stays in your browser during this demo."
              : "The image is only hashed in your browser. Nothing is uploaded."}
          </div>
        </div>
      )}
    </div>
  );
}

/**
 * One of the two landing choices.
 *
 * Styling is the selectable-card pattern already used for the AI findings list:
 * chosen is border-white/25 bg-white/10, passed-over is border-white/5
 * bg-black/10 opacity-50. Before a choice is made, Protect wears the chosen
 * treatment as its accent and Verify wears the neutral panel treatment used
 * everywhere else, so neither looks disabled.
 */
function PathCard({
  icon,
  title,
  hint,
  description,
  selected,
  dimmed,
  onClick,
}: {
  icon: React.ReactNode;
  title: string;
  hint?: string;
  description: string;
  selected: boolean;
  dimmed: boolean;
  onClick: () => void;
}) {
  // Four states, every one an existing combination from elsewhere in the app:
  //   chosen   -> border-white bg-white/10      (active dropzone, selected region)
  //   accented -> border-white/25 bg-white/10   (selected finding card)
  //   neutral  -> border-white/10 bg-white/[0.03] (every panel)
  //   passed   -> border-white/5 bg-black/10 opacity-50 (deselected finding card)
  const emphasis = selected
    ? "border-white bg-white/10"
    : dimmed
      ? "border-white/5 bg-black/10 opacity-50"
      : hint
        ? "border-white/25 bg-white/10"
        : "border-white/10 bg-white/[0.03]";

  return (
    <button
      onClick={onClick}
      aria-pressed={selected}
      className={`w-full rounded-xl border p-5 text-left transition hover:bg-white/10 ${emphasis}`}
    >
      <div className="flex items-center justify-between">
        <div className="flex h-12 w-12 items-center justify-center rounded-2xl border border-white/10 bg-white/5">
          {icon}
        </div>

        <div
          className={`flex h-5 w-5 items-center justify-center rounded-full border ${
            selected ? "border-white bg-white text-black" : "border-white/20"
          }`}
        >
          {selected && <Check size={12} />}
        </div>
      </div>

      <div className="mt-4 flex items-center gap-3">
        <span className="font-medium">{title}</span>

        {hint && !selected && !dimmed && (
          <span className="text-xs uppercase tracking-wide text-white/35">
            {hint}
          </span>
        )}
      </div>

      <p className="mt-2 text-sm leading-6 text-white/45">{description}</p>
    </button>
  );
}

function ScanningScreen({ imageUrl, modelLoading }: { imageUrl: string; modelLoading: boolean }) {
  return (
    <div className="mx-auto max-w-3xl">
      <div className="mb-6 text-center">
        <Sparkles className="mx-auto mb-4" size={24} />

        <h1 className="text-3xl font-semibold">
          {modelLoading ? "Loading AI model" : "Scanning for privacy risks"}
        </h1>

        <p className="mt-2 text-sm text-white/45">
          {modelLoading
            ? "Downloading the face detection model (~20 MB) — this only happens once."
            : "Detecting identifying information in the image."}
        </p>

        {modelLoading && (
          <div className="mx-auto mt-4 h-1.5 w-64 overflow-hidden rounded-full bg-white/10">
            <div className="h-full w-full animate-[shimmer_1.5s_ease-in-out_infinite] rounded-full bg-gradient-to-r from-transparent via-white/60 to-transparent bg-[length:200%_100%]" />
          </div>
        )}
      </div>

      <div className="relative overflow-hidden rounded-3xl border border-white/10 bg-black">
        <img
          src={imageUrl}
          alt="Uploaded"
          className="max-h-[600px] w-full object-contain opacity-80"
        />

        <div className="pointer-events-none absolute inset-x-0 top-0 h-1 animate-pulse bg-white" />
      </div>

      {!modelLoading && (
        <div className="mt-6 space-y-3">
          {[
            "Analyzing visual identity signals",
            "Checking visible text",
            "Checking location clues",
            "Preparing exposure risk map",
          ].map((item) => (
            <div
              key={item}
              className="flex items-center gap-3 rounded-xl border border-white/5 bg-white/[0.03] p-4 text-sm text-white/60"
            >
              <RefreshCw size={16} className="animate-spin" />
              {item}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function ReviewScreen({
  imageUrl,
  detections,
  toggleDetection,
  onAddManual,
  onRemoveManual,
  onContinue,
}: {
  imageUrl: string;
  detections: Detection[];
  toggleDetection: (id: string) => void;
  onAddManual: (detection: Detection) => void;
  onRemoveManual: (id: string) => void;
  onContinue: () => void;
}) {
  const [isDrawing, setIsDrawing] = useState(false);
  const [drawStart, setDrawStart] = useState<{ x: number; y: number } | null>(
    null,
  );
  const [drawCurrent, setDrawCurrent] = useState<{
    x: number;
    y: number;
  } | null>(null);
  const imgRef = useRef<HTMLImageElement>(null);

  const handleMouseDown = (e: React.MouseEvent<HTMLDivElement>) => {
    e.preventDefault();
    e.stopPropagation();
    if (!imgRef.current) return;
    const rect = imgRef.current.getBoundingClientRect();
    const x = ((e.clientX - rect.left) / rect.width) * 100;
    const y = ((e.clientY - rect.top) / rect.height) * 100;
    setDrawStart({ x, y });
    setDrawCurrent({ x, y });
    setIsDrawing(true);
  };

  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!isDrawing || !imgRef.current) return;
    e.preventDefault();
    const rect = imgRef.current.getBoundingClientRect();
    const x = ((e.clientX - rect.left) / rect.width) * 100;
    const y = ((e.clientY - rect.top) / rect.height) * 100;
    setDrawCurrent({ x, y });
  };

  const handleMouseUp = () => {
    if (!isDrawing || !drawStart || !drawCurrent) {
      setIsDrawing(false);
      return;
    }

    const minWidth = 2;
    const minHeight = 2;

    const x = Math.min(drawStart.x, drawCurrent.x);
    const y = Math.min(drawStart.y, drawCurrent.y);
    const width = Math.abs(drawCurrent.x - drawStart.x);
    const height = Math.abs(drawCurrent.y - drawStart.y);

    if (width >= minWidth && height >= minHeight) {
      const newDetection: Detection = {
        id: `manual-${Date.now()}`,
        type: "face",
        label: "Manual region",
        risk: "high",
        x,
        y,
        width,
        height,
        selected: true,
      };
      onAddManual(newDetection);
    }

    setIsDrawing(false);
    setDrawStart(null);
    setDrawCurrent(null);
  };

  const manualDetections = detections.filter((d) => d.id.startsWith("manual-"));

  return (
    <div className="grid gap-6 lg:grid-cols-[1.4fr_0.8fr]">
      <div>
        <div className="mb-4">
          <div className="flex items-center gap-2 text-sm text-white/45">
            <Eye size={15} />
            Exposure risk map
          </div>

          <h1 className="mt-2 text-2xl font-semibold md:text-3xl">
            Review sensitive regions
          </h1>
          <p className="mt-1 text-xs text-white/40">
            Click and drag to manually add regions
          </p>
        </div>

        <div
          className="relative overflow-hidden rounded-3xl border border-white/10 bg-black cursor-crosshair select-none"
          onMouseDown={handleMouseDown}
          onMouseMove={handleMouseMove}
          onMouseUp={handleMouseUp}
          onMouseLeave={handleMouseUp}
          style={{ userSelect: "none" }}
        >
          <img
            ref={imgRef}
            src={imageUrl}
            alt="Detection preview"
            className="max-h-[400px] w-full object-contain pointer-events-none md:max-h-[620px]"
            onDragStart={(e) => e.preventDefault()}
          />

          {detections.map((item) => (
            <div
              key={item.id}
              className="absolute"
              style={{
                left: `${item.x}%`,
                top: `${item.y}%`,
                width: `${item.width}%`,
                height: `${item.height}%`,
              }}
            >
              <button
                onClick={() => toggleDetection(item.id)}
                className={`w-full h-full rounded-lg border-2 transition pointer-events-auto ${
                  item.selected
                    ? "border-yellow-400 bg-yellow-400/20 shadow-lg shadow-yellow-400/50"
                    : "border-orange-400 bg-orange-400/10 opacity-75 shadow-md shadow-orange-400/30"
                }`}
                aria-label={`Toggle ${item.label}`}
              >
                <span className="absolute -top-7 left-0 whitespace-nowrap rounded-md bg-black/90 px-2 py-1 text-[10px] text-white font-semibold border border-yellow-400/50">
                  {item.label}
                </span>
              </button>
              {item.id.startsWith("manual-") && (
                <div
                  onClick={() => onRemoveManual(item.id)}
                  className="absolute -top-2 -right-2 rounded-full bg-red-500 hover:bg-red-600 p-1 cursor-pointer"
                  title="Remove this region"
                >
                  <X size={12} className="text-white" />
                </div>
              )}
            </div>
          ))}

          {isDrawing && drawStart && drawCurrent && (
            <div
              style={{
                left: `${Math.min(drawStart.x, drawCurrent.x)}%`,
                top: `${Math.min(drawStart.y, drawCurrent.y)}%`,
                width: `${Math.abs(drawCurrent.x - drawStart.x)}%`,
                height: `${Math.abs(drawCurrent.y - drawStart.y)}%`,
              }}
              className="absolute border-2 border-yellow-400 bg-yellow-400/20 rounded-lg pointer-events-none"
            />
          )}
        </div>
      </div>

      <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-5">
        <div className="text-sm text-white/45">AI findings & Manual</div>

        <div className="mt-5 space-y-3 max-h-[500px] overflow-y-auto">
          {detections.map((item) => (
            <button
              key={item.id}
              onClick={() => toggleDetection(item.id)}
              className={`w-full rounded-xl border p-4 text-left transition ${
                item.selected
                  ? "border-white/25 bg-white/10"
                  : "border-white/5 bg-black/10 opacity-50"
              }`}
            >
              <div className="flex items-center justify-between">
                <span className="font-medium">
                  {item.label}
                  {item.id.startsWith("manual-") && " (manual)"}
                </span>

                <div className="flex items-center gap-2">
                  {item.id.startsWith("manual-") && (
                    <div
                      onClick={(e) => {
                        e.stopPropagation();
                        onRemoveManual(item.id);
                      }}
                      className="text-red-400 hover:text-red-300 cursor-pointer"
                      title="Delete region"
                    >
                      <X size={14} />
                    </div>
                  )}
                  <div
                    className={`flex h-5 w-5 items-center justify-center rounded-full border ${
                      item.selected
                        ? "border-white bg-white text-black"
                        : "border-white/20"
                    }`}
                  >
                    {item.selected && <Check size={12} />}
                  </div>
                </div>
              </div>

              <div className="mt-2 text-xs text-white/40">
                Risk level: {item.risk}
              </div>
            </button>
          ))}
        </div>

        <button
          onClick={onContinue}
          disabled={detections.filter((item) => item.selected).length === 0}
          className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-medium text-black disabled:cursor-not-allowed disabled:opacity-40"
        >
          Protect selected regions
          <ChevronRight size={16} />
        </button>
      </div>
    </div>
  );
}

function ProtectingScreen({
  imageUrl,
  count,
}: {
  imageUrl: string;
  count: number;
}) {
  return (
    <div className="mx-auto max-w-3xl text-center">
      <div className="mx-auto mb-6 flex h-14 w-14 items-center justify-center rounded-2xl border border-white/10 bg-white/5">
        <ShieldCheck size={24} className="animate-pulse" />
      </div>

      <h1 className="text-3xl font-semibold">Creating protected image</h1>

      <p className="mt-3 text-white/45">
        Applying {count} approved privacy protection
        {count === 1 ? "" : "s"} and generating integrity commitments.
      </p>

      <div className="mt-8 overflow-hidden rounded-3xl border border-white/10 bg-black">
        <img
          src={imageUrl}
          alt="Processing"
          className="max-h-[520px] w-full object-contain opacity-60"
        />
      </div>

      <div className="mt-6 space-y-3 text-left">
        {[
          "Recording original image commitment",
          "Recording approved protection policy",
          "Generating protected image commitment",
          "Preparing verification statement",
        ].map((item) => (
          <div
            key={item}
            className="flex items-center gap-3 rounded-xl border border-white/5 bg-white/[0.03] p-4 text-sm"
          >
            <RefreshCw size={16} className="animate-spin" />
            {item}
          </div>
        ))}
      </div>
    </div>
  );
}

function VerifiedScreen({
  imageUrl,
  redactedUrl,
  detections,
  originalHash,
  protectedHash,
  publish,
  onPublish,
  onCancel,
  isWalletAvailable,
  onReset,
}: {
  imageUrl: string;
  redactedUrl: string | null;
  detections: Detection[];
  originalHash: string;
  protectedHash: string;
  publish: PublishState;
  onCancel: () => void;
  onPublish: () => void;
  isWalletAvailable: boolean;
  onReset: () => void;
}) {
  return (
    <div className="mx-auto max-w-4xl">
      <div className="mb-8 text-center">
        <CheckCircle2 className="mx-auto mb-4" size={44} />

        <h1 className="text-4xl font-semibold">Protection record created</h1>

        <p className="mt-3 text-white/45">
          Your image has a privacy protection policy and cryptographic integrity
          commitments ready for Midnight verification.
        </p>
      </div>

      <div className="grid items-start gap-6 md:grid-cols-2">
        <div className="self-start overflow-hidden rounded-3xl border border-white/10 bg-black">
          <img
            src={redactedUrl ?? imageUrl}
            alt="Protected image"
            className="block max-h-[500px] w-full object-contain"
          />

          {redactedUrl && (
            <a
              href={redactedUrl}
              download="truemask-protected.png"
              className="flex items-center justify-center gap-2 border-t border-white/10 px-4 py-3 text-sm text-white/70 hover:text-white"
            >
              <FileImage size={15} />
              Download protected PNG
            </a>
          )}
        </div>

        <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-6">
          <div className="flex items-center gap-2">
            <ShieldCheck size={20} />
            <span className="font-medium">Integrity record</span>
          </div>

          <div className="mt-6 space-y-5">
            <RecordItem
              label="Approved protected regions"
              value={`${detections.length} region${
                detections.length === 1 ? "" : "s"
              }`}
            />

            <RecordItem
              label="Original image commitment"
              value={shortHash(originalHash)}
              copyValue={originalHash}
            />

            <RecordItem
              label="Protected image commitment"
              value={shortHash(protectedHash)}
              copyValue={protectedHash}
            />

            <RecordItem
              label="Verification status"
              value="Ready for Midnight verification"
              success
            />
          </div>

          <div className="mt-6 rounded-xl border border-white/10 bg-black/20 p-4 text-sm leading-6 text-white/50">
            Your protected image and its commitment are ready. Anyone you send
            them to can already verify them offline. Publishing to Midnight adds
            a public record, so a reader can confirm the image independently
            instead of taking your word for the ID.
          </div>

          <PublishPanel
            publish={publish}
            onPublish={onPublish}
            onCancel={onCancel}
            isWalletAvailable={isWalletAvailable}
          />

          <button
            onClick={onReset}
            className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-medium text-black"
          >
            <FileImage size={16} />
            Protect another image
          </button>
        </div>
      </div>
    </div>
  );
}

/**
 * Publishing the record to Midnight.
 *
 * Lives only in the protect flow, because publishing is a blockchain WRITE: it
 * builds a transaction, needs a signature, and costs tDUST. Verifying is a read
 * and needs none of that, which is why nothing like this appears there.
 *
 * Styled from the existing vocabulary only: primary `rounded-xl bg-white`, the
 * `border-white/10 bg-black/20` info box, and `text-white/50` body copy.
 */
function PublishPanel({
  publish,
  onPublish,
  onCancel,
  isWalletAvailable,
}: {
  publish: PublishState;
  onPublish: () => void;
  onCancel: () => void;
  isWalletAvailable: boolean;
}) {
  if (publish.status === "done") {
    return (
      <div className="mt-6 space-y-5 rounded-xl border border-white/10 bg-black/20 p-4">
        <RecordItem label="Published to Midnight" value="Record submitted" success />

        {publish.txId && (
          <RecordItem
            label="Transaction"
            value={shortHash(publish.txId)}
            copyValue={publish.txId}
          />
        )}

        {publish.contractAddress && (
          <RecordItem
            label="Contract"
            value={shortHash(publish.contractAddress)}
            copyValue={publish.contractAddress}
          />
        )}
      </div>
    );
  }

  const busy = publish.status === "connecting" || publish.status === "publishing";
  const label =
    publish.status === "connecting"
      ? "Connecting…"
      : publish.status === "publishing"
        ? "Proving and submitting…"
        : publish.status === "error"
          ? "Try again"
          : "Connect wallet to publish";

  return (
    <div className="mt-6">
      <button
        onClick={onPublish}
        disabled={busy}
        className="flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-medium text-black transition hover:bg-white/90 disabled:cursor-not-allowed disabled:opacity-40"
      >
        <ShieldCheck size={16} />
        {label}
      </button>

      {busy && (
        <button
          onClick={onCancel}
          className="mt-2 flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-xs text-white/50 transition hover:bg-white/5"
        >
          Cancel
        </button>
      )}

      {publish.status === "publishing" && (
        <p className="mt-3 text-center text-xs text-white/30">
          Generating the zero-knowledge proof takes a moment. Keep this tab open.
        </p>
      )}

      {!isWalletAvailable && publish.status === "idle" && (
        <p className="mt-3 text-center text-xs text-white/30">
          Needs a Midnight wallet extension (Lace or 1AM). Your image and its commitment are
          already protected and verifiable without it.
        </p>
      )}

      {publish.status === "error" && (
        <div className="mt-3 rounded-xl border border-white/10 bg-black/20 p-4 text-sm leading-6 text-white/50">
          {publish.timedOut ? (
            <>
              Midnight&apos;s Preprod network has a known WebSocket reliability
              issue — other teams at this hackathon hit the same wall, and it
              isn&apos;t something a retry here can fix. Your image is already
              fully protected and cryptographically verifiable offline; publishing
              only adds a public, third-party-checkable record on top of that.
            </>
          ) : publish.needsFunds ? (
            <>
              This wallet has no tDUST to pay for the transaction. Request tNIGHT
              for your unshielded address at{" "}
              <a
                href={FAUCET_URL}
                target="_blank"
                rel="noreferrer"
                className="text-white underline underline-offset-2"
              >
                the Preprod faucet
              </a>
              , then delegate it in the wallet to generate tDUST. It takes a
              minute or two to accrue.
            </>
          ) : /wallet not found|not installed|extension/i.test(publish.message) ? (
            <>
              No Midnight wallet was detected in this browser. Install a
              Midnight wallet extension — Lace ({" "}
              <a
                href="https://docs.midnight.network"
                target="_blank"
                rel="noreferrer"
                className="text-white underline underline-offset-2"
              >
                docs.midnight.network
              </a>
              ) or 1AM ({" "}
              <a
                href="https://1am.xyz"
                target="_blank"
                rel="noreferrer"
                className="text-white underline underline-offset-2"
              >
                1am.xyz
              </a>
              ) — then reload the page.
            </>
          ) : (
            publish.message
          )}
        </div>
      )}
    </div>
  );
}

/**
 * Verify step 2 of 3: take the ID that came with the published image.
 *
 * Layout mirrors VerifiedScreen — image on the left, record panel on the right,
 * same `grid items-start gap-6 md:grid-cols-2`.
 */
function VerifyIdScreen({
  imageUrl,
  verificationId,
  setVerificationId,
  onCheck,
}: {
  imageUrl: string | null;
  verificationId: string;
  setVerificationId: (value: string) => void;
  onCheck: () => void;
}) {
  return (
    <div className="mx-auto max-w-4xl">
      <div className="mb-8 text-center">
        <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-2xl border border-white/10 bg-white/5">
          <ShieldCheck size={22} />
        </div>

        <h1 className="text-3xl font-semibold md:text-4xl">
          Enter the verification ID
        </h1>

        <p className="mt-3 text-sm text-white/45">
          The publisher shares this with the image. It is the protected image
          commitment from the integrity record.
        </p>
      </div>

      <div className="grid items-start gap-6 md:grid-cols-2">
        {imageUrl && (
          <div className="self-start overflow-hidden rounded-3xl border border-white/10 bg-black">
            <img
              src={imageUrl}
              alt="Image to check"
              className="block max-h-[500px] w-full object-contain"
            />
          </div>
        )}

        <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-6">
          <div className="flex items-center gap-2">
            <ShieldCheck size={20} />
            <span className="font-medium">Integrity check</span>
          </div>

          <div className="mt-6">
            <div className="text-xs uppercase tracking-wide text-white/35">
              Verification ID
            </div>

            <input
              value={verificationId}
              onChange={(event) => setVerificationId(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === "Enter" && verificationId.trim()) onCheck();
              }}
              placeholder="Paste the protected image commitment"
              spellCheck={false}
              autoComplete="off"
              className="mt-2 w-full break-all rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none transition placeholder:text-white/30 focus:border-white/25"
            />
          </div>

          <div className="mt-6 rounded-xl border border-white/10 bg-black/20 p-4 text-sm leading-6 text-white/50">
            TrueMask hashes the image in your browser and compares it with this
            ID. Nothing is uploaded, and no wallet is needed to run the check.
          </div>

          <button
            onClick={onCheck}
            disabled={!verificationId.trim()}
            className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-medium text-black transition hover:bg-white/90 disabled:cursor-not-allowed disabled:opacity-40"
          >
            Check this image
            <ChevronRight size={16} />
          </button>
        </div>
      </div>
    </div>
  );
}

/** Verify step 3 of 3: the answer. */
function VerifyResultScreen({
  imageUrl,
  passed,
  onChain,
  checkedHash,
  verificationId,
  onBack,
  onReset,
}: {
  imageUrl: string | null;
  passed: boolean;
  /** Result of the wallet-free indexer lookup. Additive to the local check. */
  onChain: OnChainStatus;
  checkedHash: string;
  verificationId: string;
  onBack: () => void;
  onReset: () => void;
}) {
  return (
    <div className="mx-auto max-w-4xl">
      <div className="mb-8 text-center">
        {passed ? (
          <CheckCircle2 className="mx-auto mb-4" size={44} />
        ) : (
          <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-2xl border border-white/10 bg-white/5">
            <X size={22} />
          </div>
        )}

        <h1 className="text-3xl font-semibold md:text-4xl">
          {passed
            ? "This image matches the record"
            : "This image does not match"}
        </h1>

        <p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-white/45">
          {passed
            ? "The image you were given is byte-for-byte the one the publisher protected. Nothing has been changed since."
            : "The image does not hash to the verification ID you entered. It was edited, re-saved in another format, or it is not the image this ID belongs to."}
        </p>
      </div>

      <div className="grid items-start gap-6 md:grid-cols-2">
        {imageUrl && (
          <div className="self-start overflow-hidden rounded-3xl border border-white/10 bg-black">
            <img
              src={imageUrl}
              alt="Checked image"
              className="block max-h-[500px] w-full object-contain"
            />
          </div>
        )}

        <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-6">
          <div className="flex items-center gap-2">
            <ShieldCheck size={20} />
            <span className="font-medium">Integrity record</span>
          </div>

          <div className="mt-6 space-y-5">
            <RecordItem
              label="Verification status"
              value={passed ? "Match" : "No match"}
              success={passed}
            />

            <RecordItem
              label="Verification ID"
              value={shortHash(verificationId.trim())}
              copyValue={verificationId.trim()}
            />

            <RecordItem
              label="This image hashes to"
              value={shortHash(checkedHash)}
              copyValue={checkedHash}
            />
          </div>

          <div className="mt-6 rounded-xl border border-white/10 bg-black/20 p-4 text-sm leading-6 text-white/50">
            {passed
              ? onChain === "found"
                ? "Confirmed against the record published on Midnight."
                : onChain === "absent"
                  ? "This check ran in your browser against the ID you were given. No matching record was found on Midnight yet."
                  : "This check ran entirely in your browser against the ID you were given."
              : "Check that you pasted the whole ID, and that the file was not re-encoded on its way to you."}
          </div>

          {/*
            The corrective action only leads when there is something to correct.
            On a match, moving on is the primary action; on a mismatch, a mistyped
            ID is the likeliest cause, so re-entering it comes first.
          */}
          <button
            onClick={passed ? onReset : onBack}
            className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-medium text-black transition hover:bg-white/90"
          >
            {passed ? <FileImage size={16} /> : <RefreshCw size={16} />}
            {passed ? "Check another image" : "Edit the ID"}
          </button>

          <button
            onClick={passed ? onBack : onReset}
            className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm text-white/70 transition hover:bg-white/5"
          >
            {passed ? <RefreshCw size={16} /> : <FileImage size={16} />}
            {passed ? "Edit the ID" : "Check another image"}
          </button>
        </div>
      </div>
    </div>
  );
}

function RecordItem({
  label,
  value,
  copyValue,
  success = false,
}: {
  label: string;
  value: string;
  /**
   * The full, untruncated value to put on the clipboard.
   *
   * `value` is shortened for display, so selecting it with the mouse yields the
   * ellipsis rather than the hash — which then never verifies. Anything a reader
   * has to paste back into TrueMask must pass the whole string through here.
   */
  copyValue?: string;
  success?: boolean;
}) {
  return (
    <div>
      <div className="text-xs uppercase tracking-wide text-white/35">
        {label}
      </div>

      <div className="mt-2 flex items-center justify-between gap-3">
        <div
          className={`break-all text-sm ${success ? "text-white" : "text-white/70"}`}
          title={copyValue ?? undefined}
        >
          {success && <CheckCircle2 size={15} className="mr-2 inline" />}

          {value}
        </div>

        {copyValue && <CopyButton value={copyValue} label={label} />}
      </div>
    </div>
  );
}

/**
 * Copies a full value and confirms it in place.
 *
 * Styled as the existing ghost button (border-white/10, hover:bg-white/5), just
 * square and icon-only so it sits on the same line as the value.
 */
function CopyButton({ value, label }: { value: string; label: string }) {
  const [copied, setCopied] = useState(false);

  async function copy() {
    try {
      await navigator.clipboard.writeText(value);
    } catch {
      // Clipboard API needs a secure context; fall back for plain http hosts.
      const field = document.createElement("textarea");
      field.value = value;
      field.style.position = "fixed";
      field.style.opacity = "0";
      document.body.appendChild(field);
      field.select();
      try {
        document.execCommand("copy");
      } finally {
        document.body.removeChild(field);
      }
    }
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1800);
  }

  return (
    <button
      onClick={copy}
      aria-label={copied ? `${label} copied` : `Copy ${label.toLowerCase()}`}
      title={copied ? "Copied" : "Copy full value"}
      className="shrink-0 rounded-lg border border-white/10 p-2 text-white/70 transition hover:bg-white/5"
    >
      {copied ? <Check size={15} /> : <Copy size={15} />}
    </button>
  );
}
